#!/usr/bin/env node
// Regenerates index.md (human registry), index.json (flat metadata for
// the trails-side CLI), and search.json (lightweight haystack for
// pnpm tasks search) from all RFC and story frontmatter. Idempotent —
// safe to run repeatedly; output is deterministic.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { firstHeading, loadAll, relPath, REPO_ROOT } from "./lib.mjs";

const { rfcs, stories } = loadAll();
const generatedAt = new Date().toISOString();

const rfcsSorted = [...rfcs].sort((a, b) => a.dir.localeCompare(b.dir));
const storiesSorted = [...stories].sort((a, b) => a.id.localeCompare(b.id));

// ---- index.md ----
const rows = rfcsSorted.map((r) => {
  const fm = r.frontmatter ?? {};
  const link = `[${r.dir}](${r.dir}/README.md)`;
  const title = fm.title ?? "—";
  const status = fm.status ?? "—";
  const owner = fm.owner ?? "—";
  const pkgs = Array.isArray(fm.packages) && fm.packages.length ? fm.packages.join(", ") : "—";
  return `| ${link} | ${title} | ${status} | ${owner} | ${pkgs} |`;
});
const indexMd = `# RFC index

> Auto-generated by \`scripts/build-index.mjs\` on commit. Do not edit by hand.

| RFC | Title | Status | Owner | Packages |
|-----|-------|--------|-------|----------|
${rows.join("\n")}
`;
writeFileSync(join(REPO_ROOT, "index.md"), indexMd);

// ---- index.json ----
const indexJson = {
  generated_at: generatedAt,
  rfcs: rfcsSorted.map((r) => {
    const fm = r.frontmatter ?? {};
    return {
      id: r.dir,
      title: fm.title ?? null,
      status: fm.status ?? null,
      owner: fm.owner ?? null,
      created: fm.created ?? null,
      updated: fm.updated ?? null,
      packages: fm.packages ?? [],
      clusters: fm.clusters ?? [],
      superseded_by: fm["superseded-by"] ?? null,
      related_rfcs: fm["related-rfcs"] ?? [],
      file_path: relPath(r.file),
    };
  }),
  stories: storiesSorted.map((s) => {
    const fm = s.frontmatter ?? {};
    return {
      id: s.id,
      rfc: s.rfc,
      title: fm.title ?? null,
      status: fm.status ?? null,
      cluster: fm.cluster ?? null,
      deps: fm.deps ?? [],
      deps_rfc: fm["deps-rfc"] ?? [],
      est_loc: fm["est-loc"] ?? null,
      pr: fm.pr ?? null,
      claim: fm.claim ?? null,
      assignee: fm.assignee ?? null,
      blocked_by: fm["blocked-by"] ?? null,
      file_path: relPath(s.file),
    };
  }),
};
writeFileSync(join(REPO_ROOT, "index.json"), JSON.stringify(indexJson, null, 2) + "\n");

// ---- search.json ----
const haystack = [
  ...rfcsSorted.map((r) => {
    const fm = r.frontmatter ?? {};
    return {
      id: r.dir,
      type: "rfc",
      title: fm.title ?? "",
      terms: [r.dir, fm.title, ...(fm.packages ?? []), ...(fm.clusters ?? []), firstHeading(r.body)]
        .filter(Boolean)
        .join(" ")
        .toLowerCase(),
    };
  }),
  ...storiesSorted.map((s) => {
    const fm = s.frontmatter ?? {};
    return {
      id: s.id,
      type: "story",
      title: fm.title ?? "",
      terms: [s.id, fm.title, fm.cluster, s.rfc, firstHeading(s.body)]
        .filter(Boolean)
        .join(" ")
        .toLowerCase(),
    };
  }),
];
writeFileSync(join(REPO_ROOT, "search.json"), JSON.stringify({ generated_at: generatedAt, items: haystack }, null, 2) + "\n");

console.log(`built index: ${rfcsSorted.length} RFCs, ${storiesSorted.length} stories`);
